### ISSUE TITLE
Support for feed/file cover art?

### ISSUE THREAD

**Issue by johncoxon** [herrbischoff/screaming-liquid-tiger#1]
Hi there,

It'd be cool to be able to have a file in the same folder as index.php which was called 'cover.png' or something which would be used as the artwork for the podcast in Overcast.

It'd also be cool if Overcast could display the cover art assigned to the files – at the moment they come up with empty artwork in Overcast.

This is really great though, I love it! Thanks so much for making it.

**Comment by herrbischoff** [comment]
@johncoxon: Thanks for the feedback. I was already tinkering with several approaches for this. Due to the complexity of reading MP4-style tags as opposed to ID3 ones, I finally settled on leveraging `ffmpeg` for the task.

I have just released a new version [0.2.0](https://github.com/herrbischoff/screaming-liquid-tiger/releases/tag/0.2.0) which incorporates your suggested functionality. Please let me know how it works out for you.

**Comment by johncoxon** [comment]
It works really well! I'm not advanced enough to be able to set up ffmpeg on my web server, so I had to change ffmpeg_check to false, but it gives each episode the artwork of the feed which suits me fine.

It might be worth, in a future version, instead of printing an error message if ffmpeg isn't found, just reverting to the behaviour of the script as if ffmpeg_check was false. I initially didn't set ffmpeg_check to false and it wasn't immediately obvious why Overcast stopped finding the feed.

Thanks so much!

**Comment by herrbischoff** [comment]
Good to hear it works for you. Regarding `ffmpeg`, the setup is really easy. I assume your server is running a flavor of Linux with Apache as web server.

Steps:

* Download the Linux static built binary from the official site. Direct link: http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz
* Unpack (`tar xfv ffmpeg-release-64bit-static.tar.xz`).
* Take only the file `ffmpeg` and put it in the same folder as `index.php`.
* Make sure the file's permissions are `755`.
* Set `$ffmpeg_check` back to `true`.
* Done.

To prevent unauthorized access to the binary, create a `.htaccess` file with the following content:
```apache
<files ffmpeg>
    order allow,deny
    deny from all
</files>
```

**Comment by johncoxon** [comment]
I followed your instructions, but when I go to the feed in Overcast, all the titles of the files are replaced with dashes, as shown below. The album art also doesn't appear. My files are in `.m4b` format, if that makes a difference?

![img_4517](https://cloud.githubusercontent.com/assets/1693743/11828784/a489af8a-a38f-11e5-9da5-1006156d49c7.jpg)

**Comment by herrbischoff** [comment]
Are you sure that the files are tagged correctly? Usually this is a sign of files without tags.

**Comment by johncoxon** [comment]
I use iTunes to tag them before uploading them to the server, and the album
artwork for the relevant file displays in the Overcast Now Playing window
when I play them (when ffmpeg is disabled) so I assume iTunes is setting
tags in the files correctly.

On 16 December 2015 at 01:02, Marcel Bischoff <notifications@github.com>
wrote:

> Are you sure that the files are tagged correctly? Usually this is a sign
> of files without tags.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/herrbischoff/screaming-liquid-tiger/issues/1#issuecomment-164950116>
> .
>



-- 
-- 
John Coxon
http://www.chickensinenvelopes.net/

**Comment by herrbischoff** [comment]
I have updated the script with `mediainfo` as the source of file information instead of `ffmpeg` and also set `$check_mediainfo` to `false` by default.

Could you check if this resolves your issue?

**Comment by herrbischoff** [comment]
Since there has been no update to this issue for over two weeks, I'm closing this.

**Comment by johncoxon** [comment]
So I updated my server to use mediainfo by unpacking a .deb file (intended for Ubuntu) and then uploading it to my webserver. This results in the attached screenshot, which doesn't appear to have the metadata.

![img_4895](https://cloud.githubusercontent.com/assets/1693743/12246292/a501dc50-b8a5-11e5-8387-9feaab128bba.jpg)

**Comment by johncoxon** [comment]
(When I play it the correct cover art displays, but this is the same as before.)

**Comment by herrbischoff** [comment]
Have you updated the script since?

**Comment by johncoxon** [comment]
```
Array
(
    [0] => Linux lin121.gridhost.co.uk 2.6.32.21-grsec #6 SMP Fri May 20 17:37:06 BST 2011 x86_64 x86_64 x86_64 GNU/Linux

    [1] => CentOS release 5.5 (Final)
Kernel \r on an \m


    [2] => 
    [3] => total 222860
drwxr-xr-x 2 chickens2 43191       25 Jan 16 20:42 .
drwxr-xr-x 3 chickens2 43191        3 Jan 13 08:29 ..
-rw-r--r-- 1 chickens2 43191       93 Jan  6 22:50 .htaccess
-rw-r--r-- 1 chickens2 43191 13413389 Jan 13 00:33 01 No Wi-Fi.m4a
-rw-r--r-- 1 chickens2 43191 13415892 Jan 13 00:33 02 Lazy Susan.m4a
-rw-r--r-- 1 chickens2 43191 13376772 Jan 13 00:33 03 No Friends.m4a
-rw-r--r-- 1 chickens2 43191 13232859 Jan 13 00:33 04 Wedding Anniversary.m4a
-rw-r--r-- 1 chickens2 43191 13407515 Jan 13 00:31 64-01 I'm Sorry, I Haven't a Clue 2015_11_30.m4b
-rw-r--r-- 1 chickens2 43191 13413640 Jan 13 00:31 64-02 I'm Sorry, I Haven't a Clue 2015_12_07.m4b
-rw-r--r-- 1 chickens2 43191 13371593 Jan 13 00:31 64-03 I'm Sorry, I Haven't a Clue 2015_12_14.m4b
-rw-r--r-- 1 chickens2 43191 13408070 Jan 13 00:31 64-04 I'm Sorry, I Haven't a Clue 2015_12_21.m4b
-rw-r--r-- 1 chickens2 43191 13418572 Jan 13 00:32 64-05 I'm Sorry, I Haven't a Clue 2015_12_28.m4b
-rw-r--r-- 1 chickens2 43191 13396790 Jan 13 00:32 64-06 I'm Sorry, I Haven't a Clue 2016_01_04.m4b
-rw-r--r-- 1 chickens2 43191 13344992 Jan 13 00:28 73-01 Just a Minute 2015_10_05.m4b
-rw-r--r-- 1 chickens2 43191 13349638 Jan 13 00:28 73-02 Just a Minute 2015_10_12.m4b
-rw-r--r-- 1 chickens2 43191 13187231 Jan 13 00:29 73-03 Just a Minute 2015_10_19.m4b
-rw-r--r-- 1 chickens2 43191 12957700 Jan 13 00:29 73-04 Just a Minute 2015_10_26.m4b
-rw-r--r-- 1 chickens2 43191 13361742 Jan 13 00:29 73-05 Just a Minute 2015_11_02.m4b
-rw-r--r-- 1 chickens2 43191 13371258 Jan 13 00:29 73-06 Just a Minute 2015_11_09.m4b
-rw-r--r-- 1 chickens2 43191 13068951 Jan 13 00:30 73-07 Just a Minute 2015_11_16.m4b
-rw-r--r-- 1 chickens2 43191   177036 Jan 13 00:26 comedy.png
-rw-r--r-- 1 chickens2 43191     1457 Jan 13 00:27 config.php
-rw-r--r-- 1 chickens2 43191     6349 Jan 13 00:26 index.php
-rw-r--r-- 1 chickens2 43191    72256 Jan  6 22:49 mediainfo
-rw-r--r-- 1 chickens2 43191      253 Jan 16 20:42 test.php

)
```

**Comment by johncoxon** [comment]
I should note that Firefox shows an RSS feed when I visit `index.php` but Overcast no longer seems to see any files.

**Comment by herrbischoff** [comment]
> CentOS release 5.5

Oh my dear, your hosting company does run ancient servers. However, this should have no bearing on this matter.

Could you please do another test and post the output:

```php
<?php
shell_exec("./mediainfo");
```

Also, what's the content of the `.htaccess` file? If it's anything else than password authentication, please post it as well.

**Comment by johncoxon** [comment]
So I modified the `test.php` file such that it read:

<?php
	echo "<pre>";
	$out = array();
	array_push(
	    $out,
	    shell_exec("uname -a"),
	    shell_exec("cat /etc/issue"),
	    shell_exec("which mediainfo"),
	    shell_exec("ls -la | grep -v '\.mp3$\|\.mp4$|\.m4a$|\.m4b$'"),
	    shell_exec("./mediainfo"),
		shell_exec("./mediainfo 01\ No\ Wi-Fi.m4a")
	);
	print_r($out);
	echo "</pre>";

This gave the additional lines:

	[4] => 
	[5] => 

My `.htaccess` file reads:

	AddType x-httpd-php54 .php

	<files mediainfo>
	    order allow,deny
	    deny from all
	</files>

**Comment by herrbischoff** [comment]
Well, according to your latest output, `mediainfo` does not get called at all. Probably this is a safety measure by your hosting company. You could try talking to them about it, but there's probably nothing you can do about it. Considering your host is running an ancient setup in which you have to manually set up PHP 5.4 (which has been out of support since 2014) via `.htaccess`, you may want to think about switching to a more modern provider.

Regarding SLT, you can run it without `mediainfo` support.
