### ISSUE TITLE
Files out of order

### ISSUE THREAD

**Issue by peroty** [herrbischoff/screaming-liquid-tiger#2]
I'm building an archive of an old podcast and for some reason, it puts a random episode before Episode 1.

http://enough.peroty.com/ is the live site.
Currently, Episode 79 is before 1. The last time I uploaded them, it was episode 64. The file names are consistent and I can't figure out why an episode is showing up before episode 1.

Am I missing something obvious?

**Comment by herrbischoff** [comment]
Could you paste the output of `ls -la` in that folder?

**Comment by peroty** [comment]
It’s a bit long because there’s 200+ audio files in the folder.

Here it is:

prince-george]$ ls -la
total 3495264
drwxr-xr-x  4 peroty pg71489    12288 Mar 10 19:31 .
drwx--x--- 31 peroty adm         4096 Mar 10 19:23 ..
-rw-r--r--  1 peroty pg71489  5342513 Nov 10  2013 Enough 001 - Minimal Mac Misconceptions.m4a
-rw-r--r--  1 peroty pg71489  8608330 Nov 10  2013 Enough 002 - Beware Of Information Silos.m4a
-rw-r--r--  1 peroty pg71489 10575861 Nov 10  2013 Enough 003 - iOS Minimalism.m4a
-rw-r--r--  1 peroty pg71489  9153781 Nov 10  2013 Enough 004 - Living With An 11 Inch Screen.m4a
-rw-r--r--  1 peroty pg71489 12533909 Nov 10  2013 Enough 005 - How The Podcast (Sausage) is Made.m4a
-rw-r--r--  1 peroty pg71489  6116967 Nov 10  2013 Enough 006 - Traveling Light.m4a
-rw-r--r--  1 peroty pg71489 11294358 Nov 10  2013 Enough 007 - Backup, Backup, Backup!.m4a
-rw-r--r--  1 peroty pg71489  5338682 Nov 10  2013 Enough 008 - Analog Tools - Kuru Toga.m4a
-rw-r--r--  1 peroty pg71489 11300366 Nov 10  2013 Enough 009 - The Answering Machine Problem.m4a
-rw-r--r--  1 peroty pg71489 10797756 Nov 10  2013 Enough 010 - Omnifocused.m4a
-rw-r--r--  1 peroty pg71489 10017957 Nov 10  2013 Enough 011 - Final Choices And Sensible Defaults.m4a
-rw-r--r--  1 peroty pg71489  3265003 Nov 10  2013 Enough 012 - Stuff I Love - Instapaper.m4a
-rw-r--r--  1 peroty pg71489 15617470 Nov 10  2013 Enough 013 - Cyborgs And Second Selves.m4a
-rw-r--r--  1 peroty pg71489 11899987 Nov 10  2013 Enough 014 - Dont Worry, Do.m4a
-rw-r--r--  1 peroty pg71489 11429206 Nov 10  2013 Enough 015 - Beyond The Homescreen.m4a
-rw-r--r--  1 peroty pg71489  4525283 Nov 10  2013 Enough 016 - Stuff I Love - Reeder.m4a
-rw-r--r--  1 peroty pg71489 15927243 Nov 10  2013 Enough 017 - Rambling.m4a
-rw-r--r--  1 peroty pg71489 10805287 Nov 10  2013 Enough 018 - Baked In.m4a
-rw-r--r--  1 peroty pg71489 11779009 Nov 10  2013 Enough 019 - Trusted.m4a
-rw-r--r--  1 peroty pg71489 11864355 Nov 10  2013 Enough 020 - Where We Work.m4a
-rw-r--r--  1 peroty pg71489 13057830 Nov 10  2013 Enough 021 - Paper Geek Out With Randy Murray.m4a
-rw-r--r--  1 peroty pg71489  9779811 Nov 10  2013 Enough 022 - Terry's Minimal Mac.m4a
-rw-r--r--  1 peroty pg71489 14205470 Nov 10  2013 Enough 023 - Quotebook.m4a
-rw-r--r--  1 peroty pg71489 12501302 Nov 10  2013 Enough 024 - Julio Means Business.m4a
-rw-r--r--  1 peroty pg71489 10346802 Nov 10  2013 Enough 025 - Julio's New Minimalism.m4a
-rw-r--r--  1 peroty pg71489 10672935 Nov 10  2013 Enough 026 - My Domains Are Sinking.m4a
-rw-r--r--  1 peroty pg71489 12509659 Nov 10  2013 Enough 027 - Tapbot Wars.m4a
-rw-r--r--  1 peroty pg71489 15516125 Nov 10  2013 Enough 028 - Rambling With Shawn.m4a
-rw-r--r--  1 peroty pg71489 13694992 Nov 10  2013 Enough 029 - Shawn Blanc's Minimalism.m4a
-rw-r--r--  1 peroty pg71489 12760204 Nov 10  2013 Enough 030 - Evernote Vs Yojimbo With Brett.m4a
-rw-r--r--  1 peroty pg71489 12286731 Nov 10  2013 Enough 031 - Enough For Brett.m4a
-rw-r--r--  1 peroty pg71489 12727443 Nov 10  2013 Enough 032 - Keeping It Straight.m4a
-rw-r--r--  1 peroty pg71489 12935688 Nov 10  2013 Enough 033 - Enough For Ben.m4a
-rw-r--r--  1 peroty pg71489  9794341 Nov 10  2013 Enough 034 - Nothing But Over The Air.m4a
-rw-r--r--  1 peroty pg71489  8713212 Nov 10  2013 Enough 035 - Off Button.m4a
-rw-r--r--  1 peroty pg71489  6877748 Nov 10  2013 Enough 036 - Stuff I Love - Scottevest.m4a
-rw-r--r--  1 peroty pg71489 16068896 Nov 10  2013 Enough 037 - Empty Nest.m4a
-rw-r--r--  1 peroty pg71489 11419042 Nov 10  2013 Enough 038 - Enough For Stephen.m4a
-rw-r--r--  1 peroty pg71489  8612660 Nov 10  2013 Enough 039 - NBAD.m4a
-rw-r--r--  1 peroty pg71489  8999404 Nov 10  2013 Enough 040 - French Lunch.m4a
-rw-r--r--  1 peroty pg71489 18359184 Nov 10  2013 Enough 041 - iCloudy.m4a
-rw-r--r--  1 peroty pg71489 13156539 Nov 10  2013 Enough 042 - Enough For Dave.m4a
-rw-r--r--  1 peroty pg71489 14853771 Nov 10  2013 Enough 043 - Microsocial.m4a
-rw-r--r--  1 peroty pg71489 11133687 Nov 10  2013 Enough 044 - Twitsperiment.m4a
-rw-r--r--  1 peroty pg71489 11550690 Nov 10  2013 Enough 045 - Just This.m4a
-rw-r--r--  1 peroty pg71489 15299540 Nov 10  2013 Enough 046 - iMeditate.m4a
-rw-r--r--  1 peroty pg71489 12670129 Nov 10  2013 Enough 047 - Enough.m4a
-rw-r--r--  1 peroty pg71489  7185045 Nov 10  2013 Enough 048 - Plain Text FTW.m4a
-rw-r--r--  1 peroty pg71489 13677571 Nov 10  2013 Enough 049 - Rambling Yet Again.m4a
-rw-r--r--  1 peroty pg71489 12551918 Nov 10  2013 Enough 050 - No News Is Good News.m4a
-rw-r--r--  1 peroty pg71489 12098140 Nov 10  2013 Enough 051 - Money Is A Drag.m4a
-rw-r--r--  1 peroty pg71489  6765779 Nov 10  2013 Enough 052 - Viva Quicktime.m4a
-rw-r--r--  1 peroty pg71489 14883528 Nov 10  2013 Enough 053 - Connected Disconnect.m4a
-rw-r--r--  1 peroty pg71489 14680259 Nov 10  2013 Enough 054 - State Of Mind.m4a
-rw-r--r--  1 peroty pg71489 12037168 Nov 10  2013 Enough 055 - Year Two.m4a
-rw-r--r--  1 peroty pg71489 12641461 Nov 10  2013 Enough 056 - Photopocolypse.m4a
-rw-r--r--  1 peroty pg71489 15282040 Nov 10  2013 Enough 057 - Lion Cubs.m4a
-rw-r--r--  1 peroty pg71489 15783874 Nov 10  2013 Enough 058 - Rambling With Chris Bowler.m4a
-rw-r--r--  1 peroty pg71489 11956193 Nov 10  2013 Enough 059 - Enough For Chris.m4a
-rw-r--r--  1 peroty pg71489 11620074 Nov 10  2013 Enough 060 - Digital Sabbaticals.m4a
-rw-r--r--  1 peroty pg71489 15460484 Nov 10  2013 Enough 061 - London Is Burning And So Is My Inbox.m4a
-rw-r--r--  1 peroty pg71489 13427120 Nov 10  2013 Enough 062 - Patronage.m4a
-rw-r--r--  1 peroty pg71489 13710336 Nov 10  2013 Enough 063 - Solitude.m4a
-rw-r--r--  1 peroty pg71489 19565612 Nov 10  2013 Enough 064 - Thank You Steve.m4a
-rw-r--r--  1 peroty pg71489  8921036 Nov 10  2013 Enough 065 - Stuff I Love - Byword.m4a
-rw-r--r--  1 peroty pg71489 13018766 Nov 10  2013 Enough 066 - This Is Not The Book You Are Looking For.m4a
-rw-r--r--  1 peroty pg71489 15664892 Nov 10  2013 Enough 067 - Evernote Vs Yojimbo - No Mas.m4a
-rw-r--r--  1 peroty pg71489 13130725 Nov 10  2013 Enough 068 - Mark This Tweet.m4a
-rw-r--r--  1 peroty pg71489 15457562 Nov 10  2013 Enough 069 - Coffee Talk Part 1.m4a
-rw-r--r--  1 peroty pg71489 18495737 Nov 10  2013 Enough 070 - Coffee Talk Part 2.m4a
-rw-r--r--  1 peroty pg71489 11845719 Nov 10  2013 Enough 071 - Enough For Myke.m4a
-rw-r--r--  1 peroty pg71489 15360601 Nov 10  2013 Enough 072 - A Week Without Social Networks.m4a
-rw-r--r--  1 peroty pg71489 14570612 Nov 10  2013 Enough 073 - The Future Is Coming.m4a
-rw-r--r--  1 peroty pg71489  9256752 Nov 10  2013 Enough 074 - Selfishly Social.m4a
-rw-r--r--  1 peroty pg71489 17716724 Nov 10  2013 Enough 075 - Namaste Steve.m4a
-rw-r--r--  1 peroty pg71489 16470727 Nov 10  2013 Enough 076 - The Software Story.m4a
-rw-r--r--  1 peroty pg71489 11671508 Nov 10  2013 Enough 077 - Writing Workflow.m4a
-rw-r--r--  1 peroty pg71489 17009106 Nov 10  2013 Enough 078 - Julio Goes Ding.m4a
-rw-r--r--  1 peroty pg71489 19118870 Nov 10  2013 Enough 079 - Julio-Bot.m4a
-rw-r--r--  1 peroty pg71489 16050616 Nov 10  2013 Enough 080 - Timber.m4a
-rw-r--r--  1 peroty pg71489 10328547 Nov 10  2013 Enough 081 - Local Vs Lindsay.m4a
-rw-r--r--  1 peroty pg71489 13954713 Nov 10  2013 Enough 082 - Three By Dave.m4a
-rw-r--r--  1 peroty pg71489 13084772 Nov 10  2013 Enough 083 - Hip To Be Bored.m4a
-rw-r--r--  1 peroty pg71489 13028516 Nov 10  2013 Enough 084 - NaNoFreakOutMo.m4a
-rw-r--r--  1 peroty pg71489 13631093 Nov 10  2013 Enough 085 - A Lesser Photographer.m4a
-rw-r--r--  1 peroty pg71489  9852998 Nov 10  2013 Enough 086 - Enough For CJ.m4a
-rw-r--r--  1 peroty pg71489 11186202 Nov 10  2013 Enough 087 - 5 Apps And A Dropbox.m4a
-rw-r--r--  1 peroty pg71489  8464750 Nov 10  2013 Enough 088 - Keller's Kitchen.m4a
-rw-r--r--  1 peroty pg71489 10251096 Nov 10  2013 Enough 089 - Pick A Number.m4a
-rw-r--r--  1 peroty pg71489 12105467 Nov 10  2013 Enough 090 - Not Playing Games.m4a
-rw-r--r--  1 peroty pg71489 10165635 Nov 10  2013 Enough 091 - Get Down With Markdown.m4a
-rw-r--r--  1 peroty pg71489 13821499 Nov 10  2013 Enough 092 - Occupy Tumblr.m4a
-rw-r--r--  1 peroty pg71489 16077081 Nov 10  2013 Enough 093 - How Bare Is Julio's Air.m4a
-rw-r--r--  1 peroty pg71489 13517426 Nov 10  2013 Enough 094 - iStruggle.m4a
-rw-r--r--  1 peroty pg71489 21760889 Nov 10  2013 Enough 095 - Going Home.m4a
-rw-r--r--  1 peroty pg71489 16553500 Nov 10  2013 Enough 096 - How Bare Is Mike Vardy's Air.m4a
-rw-r--r--  1 peroty pg71489 14855773 Nov 10  2013 Enough 097 - SSD FTW.m4a
-rw-r--r--  1 peroty pg71489 16824184 Nov 10  2013 Enough 098 - People And Paper.m4a
-rw-r--r--  1 peroty pg71489 13459950 Nov 10  2013 Enough 099 - How To Boil A Frog.m4a
-rw-r--r--  1 peroty pg71489 41409817 Nov 10  2013 Enough 100 - Enough 100.m4a
-rw-r--r--  1 peroty pg71489 23348694 Nov 10  2013 Enough 101 - Off The Record.m4a
-rw-r--r--  1 peroty pg71489 22458811 Nov 10  2013 Enough 102 - Home Away From Home.m4a
-rw-r--r--  1 peroty pg71489 15943750 Nov 10  2013 Enough 103 - Twittervention.m4a
-rw-r--r--  1 peroty pg71489 17435723 Nov 10  2013 Enough 104 - The Pen Addict.m4a
-rw-r--r--  1 peroty pg71489 10792736 Nov 10  2013 Enough 105 - How Bare Is Brad's Air.m4a
-rw-r--r--  1 peroty pg71489  9613987 Nov 10  2013 Enough 106 - Philosophical Discussion.m4a
-rw-r--r--  1 peroty pg71489  6726289 Nov 10  2013 Enough 107 - Graceland in the Hood.m4a
-rw-r--r--  1 peroty pg71489 11448396 Nov 10  2013 Enough 108 - Take Away The Chairs.m4a
-rw-r--r--  1 peroty pg71489 13643217 Nov 10  2013 Enough 109 - We Bring The Heavy.m4a
-rw-r--r--  1 peroty pg71489 11594019 Nov 10  2013 Enough 110 - Nothing To Chat About.m4a
-rw-r--r--  1 peroty pg71489 19216832 Nov 10  2013 Enough 111 - Duck Duck Google.m4a
-rw-r--r--  1 peroty pg71489 20453078 Nov 10  2013 Enough 112 - AsanaVaGun.m4a
-rw-r--r--  1 peroty pg71489 15024749 Nov 10  2013 Enough 113 - Fire.m4a
-rw-r--r--  1 peroty pg71489  8790929 Nov 10  2013 Enough 114 - Backup Your Cloud.m4a
-rw-r--r--  1 peroty pg71489 18010856 Nov 10  2013 Enough 115 - The Wizard Behind the Curtain.m4a
-rw-r--r--  1 peroty pg71489 14895380 Nov 10  2013 Enough 116 - Tv Is Broken.m4a
-rw-r--r--  1 peroty pg71489 14204700 Nov 10  2013 Enough 117 - How Bare Is Klifton's Air?.m4a
-rw-r--r--  1 peroty pg71489 13703213 Nov 10  2013 Enough 118 - Work With What You Have.m4a
-rw-r--r--  1 peroty pg71489 12089358 Nov 10  2013 Enough 119 - About Enough.m4a
-rw-r--r--  1 peroty pg71489 10763100 Nov 10  2013 Enough 120 - Tweetbot Wins.m4a
-rw-r--r--  1 peroty pg71489  8215353 Nov 10  2013 Enough 121 - Morning Rituals.m4a
-rw-r--r--  1 peroty pg71489 13003115 Nov 10  2013 Enough 122 - Writing Brain.m4a
-rw-r--r--  1 peroty pg71489 18908584 Nov 10  2013 Enough 123 - Release The Geniuses.m4a
-rw-r--r--  1 peroty pg71489 10385484 Nov 10  2013 Enough 124 - ADD.m4a
-rw-r--r--  1 peroty pg71489 10535473 Nov 10  2013 Enough 125 - Nothing Is Something.m4a
-rw-r--r--  1 peroty pg71489 14225671 Nov 10  2013 Enough 126 - You've Got (Too Much) Mail.m4a
-rw-r--r--  1 peroty pg71489 15096579 Nov 10  2013 Enough 127 - The Third Screen.m4a
-rw-r--r--  1 peroty pg71489  8773202 Nov 10  2013 Enough 128 - The Farmer.m4a
-rw-r--r--  1 peroty pg71489 11410387 Nov 10  2013 Enough 129 - And I Digress.m4a
-rw-r--r--  1 peroty pg71489 13615940 Nov 10  2013 Enough 130 - I Have To Run.m4a
-rw-r--r--  1 peroty pg71489 15958508 Nov 10  2013 Enough 131 - From Nobody To Peabody.m4a
-rw-r--r--  1 peroty pg71489 12672199 Nov 10  2013 Enough 132 - Nesting.m4a
-rw-r--r--  1 peroty pg71489 10532821 Nov 10  2013 Enough 133 - Where's Your Wobble.m4a
-rw-r--r--  1 peroty pg71489 22095108 Nov 10  2013 Enough 134 - Marathon.m4a
-rw-r--r--  1 peroty pg71489 12174616 Nov 10  2013 Enough 135 - Reflections.m4a
-rw-r--r--  1 peroty pg71489  9157773 Nov 10  2013 Enough 136 - Superheroes.m4a
-rw-r--r--  1 peroty pg71489 15683527 Nov 10  2013 Enough 137 - Full Screen, Paperless Pens.m4a
-rw-r--r--  1 peroty pg71489 12320885 Nov 10  2013 Enough 138 - Perfectly Natural.m4a
-rw-r--r--  1 peroty pg71489 15562361 Nov 10  2013 Enough 139 - Collections.m4a
-rw-r--r--  1 peroty pg71489  9112961 Nov 10  2013 Enough 140 - What's Broken?.m4a
-rw-r--r--  1 peroty pg71489 18967937 Nov 10  2013 Enough 141 - Primal.m4a
-rw-r--r--  1 peroty pg71489 10097049 Nov 10  2013 Enough 142 - When Friction is Fiction.m4a
-rw-r--r--  1 peroty pg71489 16611505 Nov 10  2013 Enough 143 - Frictionless.m4a
-rw-r--r--  1 peroty pg71489 10899393 Nov 10  2013 Enough 144 - Using and Loving.m4a
-rw-r--r--  1 peroty pg71489 21025441 Nov 10  2013 Enough 145 - Bischoff 3.0.m4a
-rw-r--r--  1 peroty pg71489 13557977 Nov 10  2013 Enough 146 - How Bare Is Aaron's Air?.m4a
-rw-r--r--  1 peroty pg71489 15165225 Nov 10  2013 Enough 147 - What We Believe In.m4a
-rw-r--r--  1 peroty pg71489 15250337 Nov 10  2013 Enough 148 - Rockin’ My World.m4a
-rw-r--r--  1 peroty pg71489 13503037 Nov 10  2013 Enough 149 - Ethical.m4a
-rw-r--r--  1 peroty pg71489 13115217 Nov 10  2013 Enough 150 - Men Who Stare At Globes.m4a
-rw-r--r--  1 peroty pg71489 15151249 Nov 10  2013 Enough 151 - It’s Gotta Be Da Shoes!.m4a
-rw-r--r--  1 peroty pg71489 10899149 Nov 10  2013 Enough 152 - Nike Fuel Path On The Line.m4a
-rw-r--r--  1 peroty pg71489 16975445 Nov 10  2013 Enough 153 - Awayfind.m4a
-rw-r--r--  1 peroty pg71489 15238121 Nov 10  2013 Enough 154 - Life In The Woods.m4a
-rw-r--r--  1 peroty pg71489 14481465 Nov 10  2013 Enough 155 - Email Resuscitation.m4a
-rw-r--r--  1 peroty pg71489 16526525 Nov 10  2013 Enough 156 - Is The iPad Enough.m4a
-rw-r--r--  1 peroty pg71489 10389237 Nov 10  2013 Enough 157 - Sincerely, Me.m4a
-rw-r--r--  1 peroty pg71489  5994073 Nov 10  2013 Enough 158 - Choices And Expectations.m4a
-rw-r--r--  1 peroty pg71489  7009429 Nov 10  2013 Enough 159 - Day One.m4a
-rw-r--r--  1 peroty pg71489 12383503 Nov 10  2013 Enough 160 - The No-Grade.mp3
-rw-r--r--  1 peroty pg71489 15189817 Nov 10  2013 Enough 161 - Pat.net.m4a
-rw-r--r--  1 peroty pg71489 10352649 Nov 10  2013 Enough 162 - Killing Time.m4a
-rw-r--r--  1 peroty pg71489 12904733 Nov 10  2013 Enough 163 - Scott Pilgrim vs My Pants.m4a
-rw-r--r--  1 peroty pg71489 12739041 Nov 10  2013 Enough 164 - iPad First.m4a
-rw-r--r--  1 peroty pg71489 10911645 Nov 10  2013 Enough 165 - Career Change.m4a
-rw-r--r--  1 peroty pg71489 27258285 Nov 10  2013 Enough 166 - Managing The Landscape.m4a
-rw-r--r--  1 peroty pg71489 31205485 Nov 10  2013 Enough 167 - Nice Happy Sounds.m4a
-rw-r--r--  1 peroty pg71489 21570237 Nov 10  2013 Enough 168 - Rhone Hurley 2016.m4a
-rw-r--r--  1 peroty pg71489 21995717 Nov 10  2013 Enough 169 - There's Always A Sandwich.m4a
-rw-r--r--  1 peroty pg71489 29202749 Nov 10  2013 Enough 170 - School Of Talk.m4a
-rw-r--r--  1 peroty pg71489 25083589 Nov 10  2013 Enough 171 - Upgrade You.m4a
-rw-r--r--  1 peroty pg71489 25131469 Nov 10  2013 Enough 172 - The Important Question.m4a
-rw-r--r--  1 peroty pg71489 20681237 Nov 10  2013 Enough 173 - Whole Lotta iLove.m4a
-rw-r--r--  1 peroty pg71489 16502201 Nov 10  2013 Enough 174 - Filled With Joy.m4a
-rw-r--r--  1 peroty pg71489 20549429 Nov 10  2013 Enough 175 - All Work And No Play.m4a
-rw-r--r--  1 peroty pg71489 20780213 Nov 10  2013 Enough 176 - Boring.m4a
-rw-r--r--  1 peroty pg71489 19245353 Nov 10  2013 Enough 177 - Ask Why.m4a
-rw-r--r--  1 peroty pg71489 20889709 Nov 10  2013 Enough 178 - Experience Happiness.m4a
-rw-r--r--  1 peroty pg71489 22129369 Nov 10  2013 Enough 179 - Are You Not Entertained?!.m4a
-rw-r--r--  1 peroty pg71489 18203717 Nov 10  2013 Enough 180 - Areas Of Intense Interest.m4a
-rw-r--r--  1 peroty pg71489 22197717 Nov 10  2013 Enough 181 - The Enough Holiday Spectacular.m4a
-rw-r--r--  1 peroty pg71489 22304865 Nov 10  2013 Enough 182 - Mostly Failure with Occasional Awesomeness.m4a
-rw-r--r--  1 peroty pg71489 21557555 Nov 10  2013 Enough 183 - Don't Break The Chain.m4a
-rw-r--r--  1 peroty pg71489 20831416 Nov 10  2013 Enough 184 - Have A Plan.m4a
-rw-r--r--  1 peroty pg71489 21135378 Nov 10  2013 Enough 185 - Too Heavy To Name.m4a
-rw-r--r--  1 peroty pg71489 19985156 Nov 10  2013 Enough 186 - Does Beyonce Get To Sing?.m4a
-rw-r--r--  1 peroty pg71489 17439495 Nov 10  2013 Enough 187 - Sweat Every Comma.m4a
-rw-r--r--  1 peroty pg71489 15787084 Nov 10  2013 Enough 188 - You've Never Seen What?!.m4a
-rw-r--r--  1 peroty pg71489 38419089 Nov 10  2013 Enough 189 - The Rhone Internet Protocol.m4a
-rw-r--r--  1 peroty pg71489 22119865 Nov 10  2013 Enough 190 - Read It Now.m4a
-rw-r--r--  1 peroty pg71489 24587388 Nov 10  2013 Enough 191 - Be Your Own Bad Boss.m4a
-rw-r--r--  1 peroty pg71489 19752628 Nov 10  2013 Enough 192 - A Little Bit Frazzled and Hungry.m4a
-rw-r--r--  1 peroty pg71489 14844293 Nov 10  2013 Enough 193 - Silence Is The Enemy.m4a
-rw-r--r--  1 peroty pg71489 13943081 Nov 10  2013 Enough 194 - Care Enough To Do It.mp3
-rw-r--r--  1 peroty pg71489 13925319 Nov 10  2013 Enough 195 - Extraordinary Courage.mp3
-rw-r--r--  1 peroty pg71489 21974584 Nov 10  2013 Enough 196 - Luddite In Training.mp3
-rw-r--r--  1 peroty pg71489 23739436 Nov 10  2013 Enough 197 - Reach For The Stars And Expect Nothing.mp3
-rw-r--r--  1 peroty pg71489 17945659 Nov 10  2013 Enough 198 - Turn The Key.mp3
-rw-r--r--  1 peroty pg71489 17961574 Nov 10  2013 Enough 199 - That's All I Have To Say To You.mp3
-rw-r--r--  1 peroty pg71489 23995045 Nov 10  2013 Enough 200 - A Retrospective.mp3
-rw-r--r--  1 peroty pg71489 22713485 Nov 10  2013 Enough 201 - It's Just Leisure, Man.mp3
-rw-r--r--  1 peroty pg71489 25362298 Nov 10  2013 Enough 202 - Crazy From The Heat.mp3
-rw-r--r--  1 peroty pg71489 26028053 Nov 10  2013 Enough 203 - Actions Not Apps.mp3
-rw-r--r--  1 peroty pg71489 28043341 Nov 10  2013 Enough 204 - Whirlwind.mp3
-rw-r--r--  1 peroty pg71489 26497630 Nov 10  2013 Enough 205 - WWDC Predictions.mp3
-rw-r--r--  1 peroty pg71489 18821389 Nov 10  2013 Enough 206 - Revolutionary.mp3
-rw-r--r--  1 peroty pg71489 24405223 Nov 10  2013 Enough 207 - I Am Your Undoing.mp3
-rw-r--r--  1 peroty pg71489 27098238 Nov 10  2013 Enough 208 - Last Year's Model.mp3
-rw-r--r--  1 peroty pg71489 25469134 Nov 10  2013 Enough 209 - Ten Questions.mp3
-rw-r--r--  1 peroty pg71489 20963660 Nov 10  2013 Enough 210 - Compassion, Conversation and Change.mp3
-rw-r--r--  1 peroty pg71489 28959407 Nov 10  2013 Enough 211 - Myke Has A Malfunction.mp3
-rw-r--r--  1 peroty pg71489 32662036 Nov 10  2013 Enough 212 - General Blanket Statement For All Crowdfunding.mp3
-rw-r--r--  1 peroty pg71489 29220113 Nov 10  2013 Enough 213 - Time Unmanagement.mp3
-rw-r--r--  1 peroty pg71489 21621936 Nov 10  2013 Enough 214 - Your Default Should Be No.mp3
-rw-r--r--  1 peroty pg71489 20464286 Nov 10  2013 Enough 215 - Get Back In There.mp3
-rw-r--r--  1 peroty pg71489 28079083 Nov 10  2013 Enough 216 - The Paper Addict.mp3
-rw-r--r--  1 peroty pg71489 23906175 Nov 10  2013 Enough 217 - Welcome Back.mp3
-rw-r--r--  1 peroty pg71489 25421811 Nov 10  2013 Enough 218 - Unapologetically Plastic.mp3
-rw-r--r--  1 peroty pg71489 23388956 Nov 10  2013 Enough 219 - Work Less, Do More.mp3
-rw-r--r--  1 peroty pg71489 28703197 Nov 10  2013 Enough 220 - Right Of Way.mp3
-rw-r--r--  1 peroty pg71489 28202282 Nov 10  2013 Enough 221 - Doing It For Yourself.mp3
-rw-r--r--  1 peroty pg71489 27842105 Nov 10  2013 Enough 222 - The Enough Newsletter.mp3
-rw-r--r--  1 peroty pg71489 31363305 Nov 10  2013 Enough 223 - Don't Wait To Begin.mp3
-rw-r--r--  1 peroty pg71489 21873011 Nov 10  2013 Enough 224 - Penultimate.mp3
-rw-r--r--  1 peroty pg71489 40133853 Nov 10  2013 Enough 225 - Goodbye.mp3
-rwxr-xr-x  1 peroty pg71489     4779 Feb 25 03:16 README.md
drwxr-xr-x  2 peroty pg71489       10 Mar  9 20:32 assets
-rwxr-xr-x  1 peroty pg71489     1450 Mar 10 19:17 config.php
-rwxr-xr-x  1 peroty pg71489     1473 Mar  9 20:14 config.php.default
-rw-------  1 peroty pg71489    13532 Mar  9 20:14 enough.jpg
-rw-r--r--  1 peroty adm            0 Mar 10 19:23 favicon.gif
-rw-r--r--  1 peroty adm            0 Mar 10 19:23 favicon.ico
-rwxr-xr-x  1 peroty pg71489     6831 Feb 25 03:16 index.php
-rw-r--r--  1 peroty pg71489      705 Mar 10 19:23 quickstart.html
-rwxr-xr-x  1 peroty pg71489    53998 Feb 25 03:16 screenshot.jpg

**Comment by doubtsevenhere** [comment]
I would really love this to be live - I have been searching high and low for the Enough podcast!
Please keep up the good work!
