### ISSUE TITLE
How to get feeds to Overcast

### ISSUE THREAD

**Issue by dscottfrey** [herrbischoff/screaming-liquid-tiger#3]
I seem to be unable to get Overcast to see any feeds. 

Using Mobile Safari
Selecting the directory (which contains the index.php) results in "Open this page in news?" implying that there is a feed URL being presented. Copying the same directory URL to overcast results in "Could not find a podcast feed at this URL"
Continuing on in News jumps me to Podcasts, which adds a fee that contains no episodes. 

So, not sure if I am getting a good feed and not sure how to use it

result of `ls -al` :

```
pi@raspberrypi:/media/storage/Audiobooks/Anne McCaffrey $ ls -la
total 973140
drwxrwxrwx  3 pi root      4096 Aug 16 10:17 .
drwxrwxrwx 69 pi root      4096 Aug 16 10:31 ..
-rwxrwxrwx  1 pi root      4096 Aug 15 20:50 ._All the Weyrs of Pern.m4b
-rwxrwxrwx  1 pi root 237635042 Aug 15 20:50 All the Weyrs of Pern.m4b
drwxrwxrwx  2 pi pi        4096 Aug 16 10:17 .AppleDouble
-rwxr-xr-x  1 pi pi        1449 Jul  4 08:00 config.php.default
-rwxrwxrwx  1 pi root      4096 Aug 15 20:51 ._DR1 Dragonflight.m4b
-rwxrwxrwx  1 pi root 135698786 Aug 15 20:51 DR1 Dragonflight.m4b
-rwxrwxrwx  1 pi root      4096 Aug 15 20:53 ._Dragonquest.m4b
-rwxrwxrwx  1 pi root 148205732 Aug 15 20:53 Dragonquest.m4b
-rw-r--r--  1 pi pi        6148 Aug 16 10:13 .DS_Store
-rwxr-xr-x  1 pi pi        6831 Jul  4 08:00 index.php
-rwxrwxrwx  1 pi root      4096 Aug 15 20:54 ._Runner of Pern.m4b
-rwxrwxrwx  1 pi root  82486169 Aug 15 20:54 Runner of Pern.m4b
-rwxrwxrwx  1 pi root      4096 Aug 15 20:54 ._The Skies of Pern, Part 1.m4b
-rwxrwxrwx  1 pi root  95754149 Aug 15 20:54 The Skies of Pern, Part 1.m4b
-rwxrwxrwx  1 pi root      4096 Aug 15 20:55 ._The Skies of Pern, part 2.m4b
-rwxrwxrwx  1 pi root 104476674 Aug 15 20:55 The Skies of Pern, part 2.m4b
-rwxrwxrwx  1 pi root      4096 Aug 15 20:57 ._White dragon.m4b
-rwxrwxrwx  1 pi root 192149905 Aug 15 20:57 White dragon.m4b
```

**Comment by herrbischoff** [comment]
First off, please code fence your screen output with backticks. I did it for you this one time. ;)

As I gather from your output, you are using a Raspberry Pi and from that I suppose you are running it locally. Meaning: you are using Overcast inside one of the private IP ranges. Overcast has a problem with that. I don't know why, I even contacted the author but he won't respond. Putting the same address into Apple's Podcast app (or any other one for that matter) works. Just Overcast refuses to update from local IP sources. Once you use a public IP address for the server, it works.

Sorry for not having better news. Local audiobook hosting simply does not work with Overcast for the time being. Feel free to let the author know how you feel about this, especially when you're a sponsoring (= paying) user like me.

**Comment by herrbischoff** [comment]
What I'm wondering though is if you could run `curl` on the URL (from a machine different from the Pi) and post the output here.

**Comment by dscottfrey** [comment]
> First off, please code fence your screen output with backticks. I did it for you this one time. ;)

By "code fence" do you mean 'format as code'? I haven't encountered that term (an not sure why it matters in this case)

> Just Overcast refuses to update from local IP sources. Once you use a public IP address for the server, it works.

Ah, I see. Indeed, my usual podcatcher, Downcast sees the feed. I'd hoped to use overcast to keep things separate and take advantage of it's much nicer "speedup by removing silence" feature. 
Firefox also sees the feed. Both Downcast and Firefox see every m4b file twice, one is an empty file with a proceeding period. There are OS X metadata files apparently on the drive (since I copied files there from a Mac) which I'll have to figure out how to get rid of (any easy answer to ignore .files?)

> What I'm wondering though is if you could run `curl` on the URL (from a machine different from the Pi) and post the output here.

`HMS-Imperator:test scott$ curl http://raspberrypi.local/Audiobooks/Anne%20McCaffrey/
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd"><channel><title>Audiobook Podcast</title><link>http://www.example.com</link><description>Personal Audiobook Feed</description><pubDate>Tue, 16 Aug 2016 16:19:35 America/Los_Angeles</pubDate><lastBuildDate>Tue, 16 Aug 2016 16:19:35 America/Los_Angeles</lastBuildDate><link rel="self" type="application/rss+xml"/><item><title>._All the Weyrs of Pern</title><guid isPermalink="false">http://raspberrypi.local/Audiobooks/Anne McCaffrey/._All%20the%20Weyrs%20of%20Pern.m4b</guid><enclosure url="http://raspberrypi.local/Audiobooks/Anne McCaffrey/._All%20the%20Weyrs%20of%20Pern.m4b" length="4096" type="audio/mp4"/><pubDate>Mon, 15 Aug 2016 20:50:35 America/Los_Angeles</pubDate></item><item><title>DR1 Dragonflight</title><guid isPermalink="false">http://raspberrypi.local/Audiobooks/Anne McCaffrey/DR1%20Dragonflight.m4b</guid><enclosure url="http://raspberrypi.local/Audiobooks/Anne McCaffrey/DR1%20Dragonflight.m4b" length="135698786" type="audio/mp4"/><pubDate>Mon, 15 Aug 2016 20:51:51 America/Los_Angeles</pubDate></item><item><title>Runner of Pern</title><guid isPermalink="false">http://raspberrypi.local/Audiobooks/Anne McCaffrey/Runner%20of%20Pern.m4b</guid><enclosure url="http://raspberrypi.local/Audiobooks/Anne McCaffrey/Runner%20of%20Pern.m4b" length="82486169" type="audio/mp4"/><pubDate>Mon, 15 Aug 2016 20:54:01 America/Los_Angeles</pubDate></item><item><title>._DR1 Dragonflight</title><guid isPermalink="false">http://raspberrypi.local/Audiobooks/Anne McCaffrey/._DR1%20Dragonflight.m4b</guid><enclosure url="http://raspberrypi.local/Audiobooks/Anne McCaffrey/._DR1%20Dragonflight.m4b" length="4096" type="audio/mp4"/><pubDate>Mon, 15 Aug 2016 20:51:51 America/Los_Angeles</pubDate></item><item><title>All the Weyrs of Pern</title><guid isPermalink="false">http://raspberrypi.local/Audiobooks/Anne McCaffrey/All%20the%20Weyrs%20of%20Pern.m4b</guid><enclosure url="http://raspberrypi.local/Audiobooks/Anne McCaffrey/All%20the%20Weyrs%20of%20Pern.m4b" length="237635042" type="audio/mp4"/><pubDate>Mon, 15 Aug 2016 20:50:33 America/Los_Angeles</pubDate></item><item><title>._The Skies of Pern, part 2</title><guid isPermalink="false">http://raspberrypi.local/Audiobooks/Anne McCaffrey/._The%20Skies%20of%20Pern%2C%20part%202.m4b</guid><enclosure url="http://raspberrypi.local/Audiobooks/Anne McCaffrey/._The%20Skies%20of%20Pern%2C%20part%202.m4b" length="4096" type="audio/mp4"/><pubDate>Mon, 15 Aug 2016 20:55:55 America/Los_Angeles</pubDate></item><item><title>._White dragon</title><guid isPermalink="false">http://raspberrypi.local/Audiobooks/Anne McCaffrey/._White%20dragon.m4b</guid><enclosure url="http://raspberrypi.local/Audiobooks/Anne McCaffrey/._White%20dragon.m4b" length="4096" type="audio/mp4"/><pubDate>Mon, 15 Aug 2016 20:57:44 America/Los_Angeles</pubDate></item><item><title>Dragonquest</title><guid isPermalink="false">http://raspberrypi.local/Audiobooks/Anne McCaffrey/Dragonquest.m4b</guid><enclosure url="http://raspberrypi.local/Audiobooks/Anne McCaffrey/Dragonquest.m4b" length="148205732" type="audio/mp4"/><pubDate>Mon, 15 Aug 2016 20:53:14 America/Los_Angeles</pubDate></item><item><title>._Runner of Pern</title><guid isPermalink="false">http://raspberrypi.local/Audiobooks/Anne McCaffrey/._Runner%20of%20Pern.m4b</guid><enclosure url="http://raspberrypi.local/Audiobooks/Anne McCaffrey/._Runner%20of%20Pern.m4b" length="4096" type="audio/mp4"/><pubDate>Mon, 15 Aug 2016 20:54:01 America/Los_Angeles</pubDate></item><item><title>The Skies of Pern, part 2</title><guid isPermalink="false">http://raspberrypi.local/Audiobooks/Anne McCaffrey/The%20Skies%20of%20Pern%2C%20part%202.m4b</guid><enclosure url="http://raspberrypi.local/Audiobooks/Anne McCaffrey/The%20Skies%20of%20Pern%2C%20part%202.m4b" length="104476674" type="audio/mp4"/><pubDate>Mon, 15 Aug 2016 20:55:53 America/Los_Angeles</pubDate></item><item><title>White dragon</title><guid isPermalink="false">http://raspberrypi.local/Audiobooks/Anne McCaffrey/White%20dragon.m4b</guid><enclosure url="http://raspberrypi.local/Audiobooks/Anne McCaffrey/White%20dragon.m4b" length="192149905" type="audio/mp4"/><pubDate>Mon, 15 Aug 2016 20:57:43 America/Los_Angeles</pubDate></item><item><title>The Skies of Pern, Part 1</title><guid isPermalink="false">http://raspberrypi.local/Audiobooks/Anne McCaffrey/The%20Skies%20of%20Pern%2C%20Part%201.m4b</guid><enclosure url="http://raspberrypi.local/Audiobooks/Anne McCaffrey/The%20Skies%20of%20Pern%2C%20Part%201.m4b" length="95754149" type="audio/mp4"/><pubDate>Mon, 15 Aug 2016 20:54:55 America/Los_Angeles</pubDate></item><item><title>._The Skies of Pern, Part 1</title><guid isPermalink="false">http://raspberrypi.local/Audiobooks/Anne McCaffrey/._The%20Skies%20of%20Pern%2C%20Part%201.m4b</guid><enclosure url="http://raspberrypi.local/Audiobooks/Anne McCaffrey/._The%20Skies%20of%20Pern%2C%20Part%201.m4b" length="4096" type="audio/mp4"/><pubDate>Mon, 15 Aug 2016 20:54:56 America/Los_Angeles</pubDate></item><item><title>._Dragonquest</title><guid isPermalink="false">http://raspberrypi.local/Audiobooks/Anne McCaffrey/._Dragonquest.m4b</guid><enclosure url="http://raspberrypi.local/Audiobooks/Anne McCaffrey/._Dragonquest.m4b" length="4096" type="audio/mp4"/><pubDate>Mon, 15 Aug 2016 20:53:15 America/Los_Angeles</pubDate></item></channel></rss>
HMS-Imperator:test scott$ 
`

**Comment by dscottfrey** [comment]
> (any easy answer to ignore .files?)
Nevermind. It is trivial to retroactively delete the dotfiles

**Comment by dscottfrey** [comment]
Cleaner `curl` result:
`HMS-Imperator:Volumes scott$ curl http://raspberrypi.local/Audiobooks/Anne%20McCaffrey/
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd"><channel><title>Audiobook Podcast</title><link>http://www.example.com</link><description>Personal Audiobook Feed</description><pubDate>Tue, 16 Aug 2016 17:25:39 America/Los_Angeles</pubDate><lastBuildDate>Tue, 16 Aug 2016 17:25:39 America/Los_Angeles</lastBuildDate><link rel="self" type="application/rss+xml"/><item><title>DR1 Dragonflight</title><guid isPermalink="false">http://raspberrypi.local/Audiobooks/Anne McCaffrey/DR1%20Dragonflight.m4b</guid><enclosure url="http://raspberrypi.local/Audiobooks/Anne McCaffrey/DR1%20Dragonflight.m4b" length="135698786" type="audio/mp4"/><pubDate>Mon, 15 Aug 2016 20:51:51 America/Los_Angeles</pubDate></item><item><title>Runner of Pern</title><guid isPermalink="false">http://raspberrypi.local/Audiobooks/Anne McCaffrey/Runner%20of%20Pern.m4b</guid><enclosure url="http://raspberrypi.local/Audiobooks/Anne McCaffrey/Runner%20of%20Pern.m4b" length="82486169" type="audio/mp4"/><pubDate>Mon, 15 Aug 2016 20:54:01 America/Los_Angeles</pubDate></item><item><title>All the Weyrs of Pern</title><guid isPermalink="false">http://raspberrypi.local/Audiobooks/Anne McCaffrey/All%20the%20Weyrs%20of%20Pern.m4b</guid><enclosure url="http://raspberrypi.local/Audiobooks/Anne McCaffrey/All%20the%20Weyrs%20of%20Pern.m4b" length="237635042" type="audio/mp4"/><pubDate>Mon, 15 Aug 2016 20:50:33 America/Los_Angeles</pubDate></item><item><title>Dragonquest</title><guid isPermalink="false">http://raspberrypi.local/Audiobooks/Anne McCaffrey/Dragonquest.m4b</guid><enclosure url="http://raspberrypi.local/Audiobooks/Anne McCaffrey/Dragonquest.m4b" length="148205732" type="audio/mp4"/><pubDate>Mon, 15 Aug 2016 20:53:14 America/Los_Angeles</pubDate></item><item><title>The Skies of Pern, part 2</title><guid isPermalink="false">http://raspberrypi.local/Audiobooks/Anne McCaffrey/The%20Skies%20of%20Pern%2C%20part%202.m4b</guid><enclosure url="http://raspberrypi.local/Audiobooks/Anne McCaffrey/The%20Skies%20of%20Pern%2C%20part%202.m4b" length="104476674" type="audio/mp4"/><pubDate>Mon, 15 Aug 2016 20:55:53 America/Los_Angeles</pubDate></item><item><title>White dragon</title><guid isPermalink="false">http://raspberrypi.local/Audiobooks/Anne McCaffrey/White%20dragon.m4b</guid><enclosure url="http://raspberrypi.local/Audiobooks/Anne McCaffrey/White%20dragon.m4b" length="192149905" type="audio/mp4"/><pubDate>Mon, 15 Aug 2016 20:57:43 America/Los_Angeles</pubDate></item><item><title>The Skies of Pern, Part 1</title><guid isPermalink="false">http://raspberrypi.local/Audiobooks/Anne McCaffrey/The%20Skies%20of%20Pern%2C%20Part%201.m4b</guid><enclosure url="http://raspberrypi.local/Audiobooks/Anne McCaffrey/The%20Skies%20of%20Pern%2C%20Part%201.m4b" length="95754149" type="audio/mp4"/><pubDate>Mon, 15 Aug 2016 20:54:55 America/Los_Angeles</pubDate></item></channel></rss>`

**Comment by herrbischoff** [comment]
So, everything works correctly and the culprit is indeed Overcast.

**Comment by dscottfrey** [comment]
I would say so, yes. Thanks for the good work!
